In [1]:
import pandas as pd

In [2]:
tmax = pd.read_csv('original_files/tmax.csv')
tmin = pd.read_csv('original_files/tmin.csv')

In [3]:
tmax.head(2)

,Location ID,Location,Value,Rank,Anomaly (1901-2000 base period),1901-2000 Mean
0,100,Alabama,91.3,83,0.7,90.6
1,200,Arizona,96.6,125,5.3,91.3

In [4]:
tmin.head(2)

,Location ID,Location,Value,Rank,Anomaly (1901-2000 base period),1901-2000 Mean
0,100,Alabama,36.5,86,2.3,34.2
1,200,Arizona,30.5,85,2.2,28.3

In [5]:
tmax_temp_only = tmax.drop(columns=['Location ID', 'Rank', 'Anomaly (1901-2000 base period)', '1901-2000 Mean'])
tmin_temp_only = tmin.drop(columns=['Location ID', 'Rank', 'Anomaly (1901-2000 base period)', '1901-2000 Mean'])

In [6]:
tmax_temp_only.head(2)

  Location  Value
0  Alabama   91.3
1  Arizona   96.6

In [7]:
tmin_temp_only.head(2)

  Location  Value
0  Alabama   36.5
1  Arizona   30.5

In [8]:
tmax_rename = tmax_temp_only.rename(columns={"Location": "state", "Value": "max_temp"})
tmin_rename = tmin_temp_only.rename(columns={"Location": "state", "Value": "min_temp"})

In [9]:
temp_joined = tmin_rename.join(tmax_rename, lsuffix='_caller', rsuffix='_other')

In [10]:
combined_drop = temp_joined.drop(columns=['state_other'])
combined_drop

      state_caller  min_temp  max_temp
0          Alabama      36.5      91.3
1          Arizona      30.5      96.6
2         Arkansas      32.0      90.1
3       California      36.9      91.5
4         Colorado      13.4      83.6
5      Connecticut      18.4      81.3
6         Delaware      26.5      86.0
7          Florida      47.2      91.2
8          Georgia      37.8      91.2
9            Idaho      17.8      81.8
10        Illinois      17.5      83.2
11         Indiana      19.0      83.1
12            Iowa      10.4      79.9
13          Kansas      21.6      88.3
14        Kentucky      27.1      86.7
15       Louisiana      39.7      92.5
16           Maine       4.2      75.7
17        Maryland      25.4      86.0
18   Massachusetts      17.1      80.8
19        Michigan       9.2      78.0
20       Minnesota      -2.6      76.1
21     Mississippi      36.7      91.6
22        Missouri      22.9      85.0
23         Montana      15.1      79.4
24        Nebraska      16.2      82.2
25          Nevada      24.3      89.7
26   New Hampshire       8.6      77.9
27      New Jersey      22.6      84.3
28      New Mexico      22.5      90.6
29        New York      10.1      77.8
30  North Carolina      32.2      86.8
31    North Dakota       0.9      77.6
32            Ohio      19.7      82.4
33        Oklahoma      27.7      93.6
34          Oregon      27.5      82.4
35    Pennsylvania      17.8      80.6
36    Rhode Island      20.3      81.0
37  South Carolina      36.6      90.5
38    South Dakota       8.5      79.2
39       Tennessee      30.9      87.7
40           Texas      35.5      98.2
41            Utah      17.6      88.2
42         Vermont       5.0      76.8
43        Virginia      27.3      85.6
44      Washington      28.4      79.2
45   West Virginia      24.2      83.3
46       Wisconsin       5.0      76.6
47         Wyoming      11.5      80.7

In [11]:
combined_rename = combined_drop.rename(columns={"state_caller": "state"})
combined_rename

             state  min_temp  max_temp
0          Alabama      36.5      91.3
1          Arizona      30.5      96.6
2         Arkansas      32.0      90.1
3       California      36.9      91.5
4         Colorado      13.4      83.6
5      Connecticut      18.4      81.3
6         Delaware      26.5      86.0
7          Florida      47.2      91.2
8          Georgia      37.8      91.2
9            Idaho      17.8      81.8
10        Illinois      17.5      83.2
11         Indiana      19.0      83.1
12            Iowa      10.4      79.9
13          Kansas      21.6      88.3
14        Kentucky      27.1      86.7
15       Louisiana      39.7      92.5
16           Maine       4.2      75.7
17        Maryland      25.4      86.0
18   Massachusetts      17.1      80.8
19        Michigan       9.2      78.0
20       Minnesota      -2.6      76.1
21     Mississippi      36.7      91.6
22        Missouri      22.9      85.0
23         Montana      15.1      79.4
24        Nebraska      16.2      82.2
25          Nevada      24.3      89.7
26   New Hampshire       8.6      77.9
27      New Jersey      22.6      84.3
28      New Mexico      22.5      90.6
29        New York      10.1      77.8
30  North Carolina      32.2      86.8
31    North Dakota       0.9      77.6
32            Ohio      19.7      82.4
33        Oklahoma      27.7      93.6
34          Oregon      27.5      82.4
35    Pennsylvania      17.8      80.6
36    Rhode Island      20.3      81.0
37  South Carolina      36.6      90.5
38    South Dakota       8.5      79.2
39       Tennessee      30.9      87.7
40           Texas      35.5      98.2
41            Utah      17.6      88.2
42         Vermont       5.0      76.8
43        Virginia      27.3      85.6
44      Washington      28.4      79.2
45   West Virginia      24.2      83.3
46       Wisconsin       5.0      76.6
47         Wyoming      11.5      80.7

In [12]:
state_abbr = {
"Alabama":"AL","Arizona":"AZ","Arkansas":"AR","California":"CA",
"Colorado":"CO","Connecticut":"CT","Delaware":"DE","Florida":"FL","Georgia":"GA",
"Idaho":"ID","Illinois":"IL","Indiana":"IN","Iowa":"IA","Kansas":"KS","Kentucky":"KY","Louisiana":"LA",
"Maine":"ME","Maryland":"MD","Massachusetts":"MA","Michigan":"MI","Minnesota":"MN",
"Mississippi":"MS","Missouri":"MO","Montana":"MT","Nebraska":"NE","Nevada":"NV",
"NewHampshire":"NH","NewJersey":"NJ","NewMexico":"NM","NewYork":"NY","NorthCarolina":"NC",
"NorthDakota":"ND","Ohio":"OH","Oklahoma":"OK","Oregon":"OR","Pennsylvania":"PA",
"RhodeIsland":"RI","SouthCarolina":"SC","SouthDakota":"SD","Tennessee":"TN",
"Texas":"TX","Utah":"UT","Vermont":"VT","Virginia":"VA","Washington":"WA",
"WestVirginia":"WV","Wisconsin":"WI","Wyoming":"WY"
}

In [13]:
state_df = pd.DataFrame.from_dict(state_abbr, orient='index')

In [14]:
state_index = state_df.reset_index()

In [15]:
state_rename = state_index.rename(columns={"index": "state_full", 0:"state"})
state_rename

       state_full state
0         Alabama    AL
1         Arizona    AZ
2        Arkansas    AR
3      California    CA
4        Colorado    CO
5     Connecticut    CT
6        Delaware    DE
7         Florida    FL
8         Georgia    GA
9           Idaho    ID
10       Illinois    IL
11        Indiana    IN
12           Iowa    IA
13         Kansas    KS
14       Kentucky    KY
15      Louisiana    LA
16          Maine    ME
17       Maryland    MD
18  Massachusetts    MA
19       Michigan    MI
20      Minnesota    MN
21    Mississippi    MS
22       Missouri    MO
23        Montana    MT
24       Nebraska    NE
25         Nevada    NV
26   NewHampshire    NH
27      NewJersey    NJ
28      NewMexico    NM
29        NewYork    NY
30  NorthCarolina    NC
31    NorthDakota    ND
32           Ohio    OH
33       Oklahoma    OK
34         Oregon    OR
35   Pennsylvania    PA
36    RhodeIsland    RI
37  SouthCarolina    SC
38    SouthDakota    SD
39      Tennessee    TN
40          Texas    TX
41           Utah    UT
42        Vermont    VT
43       Virginia    VA
44     Washington    WA
45   WestVirginia    WV
46      Wisconsin    WI
47        Wyoming    WY

In [16]:
state_rename

       state_full state
0         Alabama    AL
1         Arizona    AZ
2        Arkansas    AR
3      California    CA
4        Colorado    CO
5     Connecticut    CT
6        Delaware    DE
7         Florida    FL
8         Georgia    GA
9           Idaho    ID
10       Illinois    IL
11        Indiana    IN
12           Iowa    IA
13         Kansas    KS
14       Kentucky    KY
15      Louisiana    LA
16          Maine    ME
17       Maryland    MD
18  Massachusetts    MA
19       Michigan    MI
20      Minnesota    MN
21    Mississippi    MS
22       Missouri    MO
23        Montana    MT
24       Nebraska    NE
25         Nevada    NV
26   NewHampshire    NH
27      NewJersey    NJ
28      NewMexico    NM
29        NewYork    NY
30  NorthCarolina    NC
31    NorthDakota    ND
32           Ohio    OH
33       Oklahoma    OK
34         Oregon    OR
35   Pennsylvania    PA
36    RhodeIsland    RI
37  SouthCarolina    SC
38    SouthDakota    SD
39      Tennessee    TN
40          Texas    TX
41           Utah    UT
42        Vermont    VT
43       Virginia    VA
44     Washington    WA
45   WestVirginia    WV
46      Wisconsin    WI
47        Wyoming    WY

In [17]:
temp_state_abbr = combined_rename.join(state_rename, lsuffix='_caller', rsuffix='_other')

In [18]:
temp_state_abbr

      state_caller  min_temp  max_temp     state_full state_other
0          Alabama      36.5      91.3        Alabama          AL
1          Arizona      30.5      96.6        Arizona          AZ
2         Arkansas      32.0      90.1       Arkansas          AR
3       California      36.9      91.5     California          CA
4         Colorado      13.4      83.6       Colorado          CO
5      Connecticut      18.4      81.3    Connecticut          CT
6         Delaware      26.5      86.0       Delaware          DE
7          Florida      47.2      91.2        Florida          FL
8          Georgia      37.8      91.2        Georgia          GA
9            Idaho      17.8      81.8          Idaho          ID
10        Illinois      17.5      83.2       Illinois          IL
11         Indiana      19.0      83.1        Indiana          IN
12            Iowa      10.4      79.9           Iowa          IA
13          Kansas      21.6      88.3         Kansas          KS
14        Kentucky      27.1      86.7       Kentucky          KY
15       Louisiana      39.7      92.5      Louisiana          LA
16           Maine       4.2      75.7          Maine          ME
17        Maryland      25.4      86.0       Maryland          MD
18   Massachusetts      17.1      80.8  Massachusetts          MA
19        Michigan       9.2      78.0       Michigan          MI
20       Minnesota      -2.6      76.1      Minnesota          MN
21     Mississippi      36.7      91.6    Mississippi          MS
22        Missouri      22.9      85.0       Missouri          MO
23         Montana      15.1      79.4        Montana          MT
24        Nebraska      16.2      82.2       Nebraska          NE
25          Nevada      24.3      89.7         Nevada          NV
26   New Hampshire       8.6      77.9   NewHampshire          NH
27      New Jersey      22.6      84.3      NewJersey          NJ
28      New Mexico      22.5      90.6      NewMexico          NM
29        New York      10.1      77.8        NewYork          NY
30  North Carolina      32.2      86.8  NorthCarolina          NC
31    North Dakota       0.9      77.6    NorthDakota          ND
32            Ohio      19.7      82.4           Ohio          OH
33        Oklahoma      27.7      93.6       Oklahoma          OK
34          Oregon      27.5      82.4         Oregon          OR
35    Pennsylvania      17.8      80.6   Pennsylvania          PA
36    Rhode Island      20.3      81.0    RhodeIsland          RI
37  South Carolina      36.6      90.5  SouthCarolina          SC
38    South Dakota       8.5      79.2    SouthDakota          SD
39       Tennessee      30.9      87.7      Tennessee          TN
40           Texas      35.5      98.2          Texas          TX
41            Utah      17.6      88.2           Utah          UT
42         Vermont       5.0      76.8        Vermont          VT
43        Virginia      27.3      85.6       Virginia          VA
44      Washington      28.4      79.2     Washington          WA
45   West Virginia      24.2      83.3   WestVirginia          WV
46       Wisconsin       5.0      76.6      Wisconsin          WI
47         Wyoming      11.5      80.7        Wyoming          WY

In [19]:
temp_combo_drop = temp_state_abbr.drop(columns=['state_full'])
temp_combo_drop

      state_caller  min_temp  max_temp state_other
0          Alabama      36.5      91.3          AL
1          Arizona      30.5      96.6          AZ
2         Arkansas      32.0      90.1          AR
3       California      36.9      91.5          CA
4         Colorado      13.4      83.6          CO
5      Connecticut      18.4      81.3          CT
6         Delaware      26.5      86.0          DE
7          Florida      47.2      91.2          FL
8          Georgia      37.8      91.2          GA
9            Idaho      17.8      81.8          ID
10        Illinois      17.5      83.2          IL
11         Indiana      19.0      83.1          IN
12            Iowa      10.4      79.9          IA
13          Kansas      21.6      88.3          KS
14        Kentucky      27.1      86.7          KY
15       Louisiana      39.7      92.5          LA
16           Maine       4.2      75.7          ME
17        Maryland      25.4      86.0          MD
18   Massachusetts      17.1      80.8          MA
19        Michigan       9.2      78.0          MI
20       Minnesota      -2.6      76.1          MN
21     Mississippi      36.7      91.6          MS
22        Missouri      22.9      85.0          MO
23         Montana      15.1      79.4          MT
24        Nebraska      16.2      82.2          NE
25          Nevada      24.3      89.7          NV
26   New Hampshire       8.6      77.9          NH
27      New Jersey      22.6      84.3          NJ
28      New Mexico      22.5      90.6          NM
29        New York      10.1      77.8          NY
30  North Carolina      32.2      86.8          NC
31    North Dakota       0.9      77.6          ND
32            Ohio      19.7      82.4          OH
33        Oklahoma      27.7      93.6          OK
34          Oregon      27.5      82.4          OR
35    Pennsylvania      17.8      80.6          PA
36    Rhode Island      20.3      81.0          RI
37  South Carolina      36.6      90.5          SC
38    South Dakota       8.5      79.2          SD
39       Tennessee      30.9      87.7          TN
40           Texas      35.5      98.2          TX
41            Utah      17.6      88.2          UT
42         Vermont       5.0      76.8          VT
43        Virginia      27.3      85.6          VA
44      Washington      28.4      79.2          WA
45   West Virginia      24.2      83.3          WV
46       Wisconsin       5.0      76.6          WI
47         Wyoming      11.5      80.7          WY

In [20]:
temp_min_max = temp_combo_drop.rename(columns={"state_caller": "state_full", "state_other":"state"})

In [21]:
temp_min_max

        state_full  min_temp  max_temp state
0          Alabama      36.5      91.3    AL
1          Arizona      30.5      96.6    AZ
2         Arkansas      32.0      90.1    AR
3       California      36.9      91.5    CA
4         Colorado      13.4      83.6    CO
5      Connecticut      18.4      81.3    CT
6         Delaware      26.5      86.0    DE
7          Florida      47.2      91.2    FL
8          Georgia      37.8      91.2    GA
9            Idaho      17.8      81.8    ID
10        Illinois      17.5      83.2    IL
11         Indiana      19.0      83.1    IN
12            Iowa      10.4      79.9    IA
13          Kansas      21.6      88.3    KS
14        Kentucky      27.1      86.7    KY
15       Louisiana      39.7      92.5    LA
16           Maine       4.2      75.7    ME
17        Maryland      25.4      86.0    MD
18   Massachusetts      17.1      80.8    MA
19        Michigan       9.2      78.0    MI
20       Minnesota      -2.6      76.1    MN
21     Mississippi      36.7      91.6    MS
22        Missouri      22.9      85.0    MO
23         Montana      15.1      79.4    MT
24        Nebraska      16.2      82.2    NE
25          Nevada      24.3      89.7    NV
26   New Hampshire       8.6      77.9    NH
27      New Jersey      22.6      84.3    NJ
28      New Mexico      22.5      90.6    NM
29        New York      10.1      77.8    NY
30  North Carolina      32.2      86.8    NC
31    North Dakota       0.9      77.6    ND
32            Ohio      19.7      82.4    OH
33        Oklahoma      27.7      93.6    OK
34          Oregon      27.5      82.4    OR
35    Pennsylvania      17.8      80.6    PA
36    Rhode Island      20.3      81.0    RI
37  South Carolina      36.6      90.5    SC
38    South Dakota       8.5      79.2    SD
39       Tennessee      30.9      87.7    TN
40           Texas      35.5      98.2    TX
41            Utah      17.6      88.2    UT
42         Vermont       5.0      76.8    VT
43        Virginia      27.3      85.6    VA
44      Washington      28.4      79.2    WA
45   West Virginia      24.2      83.3    WV
46       Wisconsin       5.0      76.6    WI
47         Wyoming      11.5      80.7    WY

In [22]:
temp_min_max['temp_range'] = temp_min_max['max_temp'] - temp_min_max['min_temp']

In [27]:
temp_min_max

        state_full  min_temp  max_temp state  temp_range
0          Alabama      36.5      91.3    AL        54.8
1          Arizona      30.5      96.6    AZ        66.1
2         Arkansas      32.0      90.1    AR        58.1
3       California      36.9      91.5    CA        54.6
4         Colorado      13.4      83.6    CO        70.2
5      Connecticut      18.4      81.3    CT        62.9
6         Delaware      26.5      86.0    DE        59.5
7          Florida      47.2      91.2    FL        44.0
8          Georgia      37.8      91.2    GA        53.4
9            Idaho      17.8      81.8    ID        64.0
10        Illinois      17.5      83.2    IL        65.7
11         Indiana      19.0      83.1    IN        64.1
12            Iowa      10.4      79.9    IA        69.5
13          Kansas      21.6      88.3    KS        66.7
14        Kentucky      27.1      86.7    KY        59.6
15       Louisiana      39.7      92.5    LA        52.8
16           Maine       4.2      75.7    ME        71.5
17        Maryland      25.4      86.0    MD        60.6
18   Massachusetts      17.1      80.8    MA        63.7
19        Michigan       9.2      78.0    MI        68.8
20       Minnesota      -2.6      76.1    MN        78.7
21     Mississippi      36.7      91.6    MS        54.9
22        Missouri      22.9      85.0    MO        62.1
23         Montana      15.1      79.4    MT        64.3
24        Nebraska      16.2      82.2    NE        66.0
25          Nevada      24.3      89.7    NV        65.4
26   New Hampshire       8.6      77.9    NH        69.3
27      New Jersey      22.6      84.3    NJ        61.7
28      New Mexico      22.5      90.6    NM        68.1
29        New York      10.1      77.8    NY        67.7
30  North Carolina      32.2      86.8    NC        54.6
31    North Dakota       0.9      77.6    ND        76.7
32            Ohio      19.7      82.4    OH        62.7
33        Oklahoma      27.7      93.6    OK        65.9
34          Oregon      27.5      82.4    OR        54.9
35    Pennsylvania      17.8      80.6    PA        62.8
36    Rhode Island      20.3      81.0    RI        60.7
37  South Carolina      36.6      90.5    SC        53.9
38    South Dakota       8.5      79.2    SD        70.7
39       Tennessee      30.9      87.7    TN        56.8
40           Texas      35.5      98.2    TX        62.7
41            Utah      17.6      88.2    UT        70.6
42         Vermont       5.0      76.8    VT        71.8
43        Virginia      27.3      85.6    VA        58.3
44      Washington      28.4      79.2    WA        50.8
45   West Virginia      24.2      83.3    WV        59.1
46       Wisconsin       5.0      76.6    WI        71.6
47         Wyoming      11.5      80.7    WY        69.2

In [25]:
temp_min_max['temp_range'].min()

44.0

In [26]:
temp_min_max['temp_range'].max()

78.69999999999999

In [29]:
temp_min_max.to_csv("temp_min_and_max.csv", index=False)