In [32]:
import pandas as pd

In [33]:
population = pd.read_csv('../population/population_categories.csv')
population

            state                  city  population pop_cat
0        New York              New York     8175133   large
1      California           Los Angeles     3792621   large
2        Illinois               Chicago     2695598   large
3        New York              Brooklyn     2533000   large
4        New York                Queens     2230772   large
...           ...                   ...         ...     ...
19565      Alaska               Wasilla        7831  middle
19566      Alaska        White Mountain         190   small
19567      Alaska              Whittier         220   small
19568      Alaska                Willow        2102   small
19569      Alaska  Wrangell and borough        2369   small

[19570 rows x 4 columns]

In [34]:
# population['population'] = population['population'].str.replace(',', '')

In [35]:
population.loc[:,'population'] = population.loc[:, 'population'].astype(int)

In [36]:
population_sorted = population.sort_values(by=['state', 'city'])
population_sorted

         state        city  population pop_cat
6579   Alabama   Abbeville        2688  middle
5007   Alabama  Adamsville        4522  middle
11638  Alabama     Addison         758   small
14827  Alabama       Akron         356   small
1237   Alabama   Alabaster       30352  middle
...        ...         ...         ...     ...
13891  Wyoming   Wamsutter         451   small
5653   Wyoming   Wheatland        3627  middle
4490   Wyoming     Worland        5487  middle
8047   Wyoming      Wright        1807   small
17591  Wyoming       Yoder         151   small

[19570 rows x 4 columns]

In [37]:
temp_data = pd.read_csv('../temperature/original_files/redfin_temps_complete.csv')
temp_data

         temp_city temp_state temp_abbr  Summer Temp  Winter Temp
0        Alabaster    Alabama        AL         90.0         34.0
1          Ardmore    Alabama        AL         89.0         28.0
2           Athens    Alabama        AL         89.0         28.0
3         Bessemer    Alabama        AL         91.0         33.0
4       Birmingham    Alabama        AL         82.0         45.0
..             ...        ...       ...          ...          ...
555         Sutton     Alaska        AK         66.0          7.0
556      Talkeetna     Alaska        AK         65.0          6.0
557  Trapper Creek     Alaska        AK         65.0          6.0
558        Wasilla     Alaska        AK         68.0          7.0
559         Willow     Alaska        AK         68.0          7.0

[560 rows x 5 columns]

In [38]:
temp_data_sorted = temp_data.sort_values(by=['temp_state', 'temp_city'])
temp_data_sorted

        temp_city temp_state temp_abbr  Summer Temp  Winter Temp
0       Alabaster    Alabama        AL         90.0         34.0
1         Ardmore    Alabama        AL         89.0         28.0
2          Athens    Alabama        AL         89.0         28.0
3        Bessemer    Alabama        AL         91.0         33.0
4      Birmingham    Alabama        AL         82.0         45.0
..            ...        ...       ...          ...          ...
523  Williams Bay  Wisconsin        WI         80.0         10.0
524        Casper    Wyoming        WY         69.7         26.9
525      Cheyenne    Wyoming        WY         70.5         31.0
526        Lander    Wyoming        WY         70.9         17.9
527      Sheridan    Wyoming        WY         69.3         27.1

[560 rows x 5 columns]

In [39]:
temp_data_sorted.dtypes

temp_city       object
temp_state      object
temp_abbr       object
Summer Temp    float64
Winter Temp    float64
dtype: object

In [40]:

temp_data_sorted.loc[:,'temp_city'] = temp_data_sorted.loc[:, 'temp_city'].astype("string")
temp_data_sorted.loc[:,'temp_state'] = temp_data_sorted.loc[:, 'temp_state'].astype("string")
temp_data_sorted.loc[:,'temp_abbr'] = temp_data_sorted.loc[:, 'temp_abbr'].astype("string")

In [41]:
temp_data_sorted.dtypes

temp_city       string
temp_state      string
temp_abbr       string
Summer Temp    float64
Winter Temp    float64
dtype: object

In [42]:
pop_temp_merge = temp_data_sorted.merge(population_sorted, how="left", left_on=['temp_state', 'temp_city'], right_on=['state', 'city'])

In [43]:
pop_temp_merge

,temp_city,temp_state,temp_abbr,Summer Temp,Winter Temp,state,city,population,pop_cat
0,Alabaster,Alabama,AL,90.0,34.0,Alabama,Alabaster,30352.0,middle
1,Ardmore,Alabama,AL,89.0,28.0,Alabama,Ardmore,1194.0,small
2,Athens,Alabama,AL,89.0,28.0,Alabama,Athens,21897.0,middle
3,Bessemer,Alabama,AL,91.0,33.0,Alabama,Bessemer,27456.0,middle
4,Birmingham,Alabama,AL,82.0,45.0,Alabama,Birmingham,212237.0,large
...,...,...,...,...,...,...,...,...,...
555,Williams Bay,Wisconsin,WI,80.0,10.0,Wisconsin,Williams Bay,2564.0,middle
556,Casper,Wyoming,WY,69.7,26.9,Wyoming,Casper,55316.0,large
557,Cheyenne,Wyoming,WY,70.5,31.0,Wyoming,Cheyenne,59466.0,large
558,Lander,Wyoming,WY,70.9,17.9,Wyoming,Lander,7487.0,middle
559,Sheridan,Wyoming,WY,69.3,27.1,Wyoming,Sheridan,17444.0,middle

In [44]:
pop_temp_drop_col = pop_temp_merge.drop(columns=['state', 'city'])

In [45]:
pop_temp_drop_col

,temp_city,temp_state,temp_abbr,Summer Temp,Winter Temp,population,pop_cat
0,Alabaster,Alabama,AL,90.0,34.0,30352.0,middle
1,Ardmore,Alabama,AL,89.0,28.0,1194.0,small
2,Athens,Alabama,AL,89.0,28.0,21897.0,middle
3,Bessemer,Alabama,AL,91.0,33.0,27456.0,middle
4,Birmingham,Alabama,AL,82.0,45.0,212237.0,large
...,...,...,...,...,...,...,...
555,Williams Bay,Wisconsin,WI,80.0,10.0,2564.0,middle
556,Casper,Wyoming,WY,69.7,26.9,55316.0,large
557,Cheyenne,Wyoming,WY,70.5,31.0,59466.0,large
558,Lander,Wyoming,WY,70.9,17.9,7487.0,middle
559,Sheridan,Wyoming,WY,69.3,27.1,17444.0,middle

## JOINING HOUSING

In [46]:
redfin_data = pd.read_csv('../redfin_housing/redfin_resources/combined_regions/redfin_all_regions.csv')

In [47]:
redfin_data

,Unnamed: 0,property_type,address,city,state,zip_code,price,beds,baths,square_feet,lot_size,year_built,hoa_permonth,url,latitude,longitude
0,4870,Single Family Residential,32996 Heather Glen Ct,Anchor Point,AK,99556.0,369900.0,5.0,3.00,2500.0,404672.0,2016.0,0.0,http://www.redfin.com/AK/Unknown/32996-HEATHER...,59.794550,-151.827787
1,4871,Single Family Residential,70875 Lee Roy Ave,Anchor Point,AK,99556.0,319000.0,2.0,2.00,1456.0,125452.0,2002.0,0.0,http://www.redfin.com/AK/Anchor-Point/70875-Le...,59.845004,-151.787534
2,4872,Single Family Residential,26890 Sterling Hwy,Anchor Point,AK,99556.0,115000.0,2.0,1.00,896.0,86248.0,2009.0,0.0,http://www.redfin.com/AK/Anchor-Point/26890-St...,59.882706,-151.782732
3,4873,Single Family Residential,31513 Sterling Hwy,Anchor Point,AK,99556.0,205000.0,3.0,1.00,1423.0,78408.0,1962.0,0.0,http://www.redfin.com/AK/Anchor-Point/31513-St...,59.816224,-151.827229
4,4874,Single Family Residential,72960 Laida Ave,Anchor Point,AK,99556.0,299000.0,2.0,2.00,2185.0,78843.0,1998.0,0.0,http://www.redfin.com/AK/Anchor-Point/72960-La...,59.781840,-151.851596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11179,4868,Townhouse,2705 SW Sylvan Heights Dr,Seattle,WA,98106,515000.0,2.0,2.25,1420.0,1245.0,2007.0,190.0,http://www.redfin.com/WA/Seattle/2705-SW-Sylva...,47.539596,-122.368164
11180,2434,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,6135.0,1947.0,0.0,http://www.redfin.com/WA/Shoreline/3020-NE-145...,47.734004,-122.295562
11181,4869,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,6135.0,1947.0,0.0,http://www.redfin.com/WA/Shoreline/3020-NE-145...,47.734004,-122.295562
11182,2085,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,0.0,2001.0,237.0,http://www.redfin.com/WA/Vancouver/730-SE-Fair...,45.615925,-122.652918
11183,4520,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,0.0,2001.0,237.0,http://www.redfin.com/WA/Vancouver/730-SE-Fair...,45.615925,-122.652918

In [48]:
redfin_sort_state = redfin_data.sort_values(by=['state', 'city'])
redfin_sort_state

,Unnamed: 0,property_type,address,city,state,zip_code,price,beds,baths,square_feet,lot_size,year_built,hoa_permonth,url,latitude,longitude
0,4870,Single Family Residential,32996 Heather Glen Ct,Anchor Point,AK,99556.0,369900.0,5.0,3.00,2500.0,404672.0,2016.0,0.0,http://www.redfin.com/AK/Unknown/32996-HEATHER...,59.794550,-151.827787
1,4871,Single Family Residential,70875 Lee Roy Ave,Anchor Point,AK,99556.0,319000.0,2.0,2.00,1456.0,125452.0,2002.0,0.0,http://www.redfin.com/AK/Anchor-Point/70875-Le...,59.845004,-151.787534
2,4872,Single Family Residential,26890 Sterling Hwy,Anchor Point,AK,99556.0,115000.0,2.0,1.00,896.0,86248.0,2009.0,0.0,http://www.redfin.com/AK/Anchor-Point/26890-St...,59.882706,-151.782732
3,4873,Single Family Residential,31513 Sterling Hwy,Anchor Point,AK,99556.0,205000.0,3.0,1.00,1423.0,78408.0,1962.0,0.0,http://www.redfin.com/AK/Anchor-Point/31513-St...,59.816224,-151.827229
4,4874,Single Family Residential,72960 Laida Ave,Anchor Point,AK,99556.0,299000.0,2.0,2.00,2185.0,78843.0,1998.0,0.0,http://www.redfin.com/AK/Anchor-Point/72960-La...,59.781840,-151.851596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11179,4868,Townhouse,2705 SW Sylvan Heights Dr,Seattle,WA,98106,515000.0,2.0,2.25,1420.0,1245.0,2007.0,190.0,http://www.redfin.com/WA/Seattle/2705-SW-Sylva...,47.539596,-122.368164
11180,2434,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,6135.0,1947.0,0.0,http://www.redfin.com/WA/Shoreline/3020-NE-145...,47.734004,-122.295562
11181,4869,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,6135.0,1947.0,0.0,http://www.redfin.com/WA/Shoreline/3020-NE-145...,47.734004,-122.295562
11182,2085,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,0.0,2001.0,237.0,http://www.redfin.com/WA/Vancouver/730-SE-Fair...,45.615925,-122.652918
11183,4520,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,0.0,2001.0,237.0,http://www.redfin.com/WA/Vancouver/730-SE-Fair...,45.615925,-122.652918

In [49]:
redfin_sort_dropna = redfin_sort_state.dropna()
redfin_sort_dropna

,Unnamed: 0,property_type,address,city,state,zip_code,price,beds,baths,square_feet,lot_size,year_built,hoa_permonth,url,latitude,longitude
0,4870,Single Family Residential,32996 Heather Glen Ct,Anchor Point,AK,99556.0,369900.0,5.0,3.00,2500.0,404672.0,2016.0,0.0,http://www.redfin.com/AK/Unknown/32996-HEATHER...,59.794550,-151.827787
1,4871,Single Family Residential,70875 Lee Roy Ave,Anchor Point,AK,99556.0,319000.0,2.0,2.00,1456.0,125452.0,2002.0,0.0,http://www.redfin.com/AK/Anchor-Point/70875-Le...,59.845004,-151.787534
2,4872,Single Family Residential,26890 Sterling Hwy,Anchor Point,AK,99556.0,115000.0,2.0,1.00,896.0,86248.0,2009.0,0.0,http://www.redfin.com/AK/Anchor-Point/26890-St...,59.882706,-151.782732
3,4873,Single Family Residential,31513 Sterling Hwy,Anchor Point,AK,99556.0,205000.0,3.0,1.00,1423.0,78408.0,1962.0,0.0,http://www.redfin.com/AK/Anchor-Point/31513-St...,59.816224,-151.827229
4,4874,Single Family Residential,72960 Laida Ave,Anchor Point,AK,99556.0,299000.0,2.0,2.00,2185.0,78843.0,1998.0,0.0,http://www.redfin.com/AK/Anchor-Point/72960-La...,59.781840,-151.851596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11179,4868,Townhouse,2705 SW Sylvan Heights Dr,Seattle,WA,98106,515000.0,2.0,2.25,1420.0,1245.0,2007.0,190.0,http://www.redfin.com/WA/Seattle/2705-SW-Sylva...,47.539596,-122.368164
11180,2434,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,6135.0,1947.0,0.0,http://www.redfin.com/WA/Shoreline/3020-NE-145...,47.734004,-122.295562
11181,4869,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,6135.0,1947.0,0.0,http://www.redfin.com/WA/Shoreline/3020-NE-145...,47.734004,-122.295562
11182,2085,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,0.0,2001.0,237.0,http://www.redfin.com/WA/Vancouver/730-SE-Fair...,45.615925,-122.652918
11183,4520,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,0.0,2001.0,237.0,http://www.redfin.com/WA/Vancouver/730-SE-Fair...,45.615925,-122.652918

In [50]:
pop_temp_drop_col.sort_values(by=['temp_state', 'temp_city'])
pop_temp_drop_col

,temp_city,temp_state,temp_abbr,Summer Temp,Winter Temp,population,pop_cat
0,Alabaster,Alabama,AL,90.0,34.0,30352.0,middle
1,Ardmore,Alabama,AL,89.0,28.0,1194.0,small
2,Athens,Alabama,AL,89.0,28.0,21897.0,middle
3,Bessemer,Alabama,AL,91.0,33.0,27456.0,middle
4,Birmingham,Alabama,AL,82.0,45.0,212237.0,large
...,...,...,...,...,...,...,...
555,Williams Bay,Wisconsin,WI,80.0,10.0,2564.0,middle
556,Casper,Wyoming,WY,69.7,26.9,55316.0,large
557,Cheyenne,Wyoming,WY,70.5,31.0,59466.0,large
558,Lander,Wyoming,WY,70.9,17.9,7487.0,middle
559,Sheridan,Wyoming,WY,69.3,27.1,17444.0,middle

In [51]:
housing_complete_merge = redfin_sort_dropna.merge(pop_temp_drop_col, how="left", left_on=['state', 'city'], right_on=['temp_abbr', 'temp_city'])
housing_complete_merge

,Unnamed: 0,property_type,address,city,state,zip_code,price,beds,baths,square_feet,...,url,latitude,longitude,temp_city,temp_state,temp_abbr,Summer Temp,Winter Temp,population,pop_cat
0,4870,Single Family Residential,32996 Heather Glen Ct,Anchor Point,AK,99556.0,369900.0,5.0,3.00,2500.0,...,http://www.redfin.com/AK/Unknown/32996-HEATHER...,59.794550,-151.827787,Anchor Point,Alaska,AK,61.0,19.0,1930.0,small
1,4871,Single Family Residential,70875 Lee Roy Ave,Anchor Point,AK,99556.0,319000.0,2.0,2.00,1456.0,...,http://www.redfin.com/AK/Anchor-Point/70875-Le...,59.845004,-151.787534,Anchor Point,Alaska,AK,61.0,19.0,1930.0,small
2,4872,Single Family Residential,26890 Sterling Hwy,Anchor Point,AK,99556.0,115000.0,2.0,1.00,896.0,...,http://www.redfin.com/AK/Anchor-Point/26890-St...,59.882706,-151.782732,Anchor Point,Alaska,AK,61.0,19.0,1930.0,small
3,4873,Single Family Residential,31513 Sterling Hwy,Anchor Point,AK,99556.0,205000.0,3.0,1.00,1423.0,...,http://www.redfin.com/AK/Anchor-Point/31513-St...,59.816224,-151.827229,Anchor Point,Alaska,AK,61.0,19.0,1930.0,small
4,4874,Single Family Residential,72960 Laida Ave,Anchor Point,AK,99556.0,299000.0,2.0,2.00,2185.0,...,http://www.redfin.com/AK/Anchor-Point/72960-La...,59.781840,-151.851596,Anchor Point,Alaska,AK,61.0,19.0,1930.0,small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10025,4868,Townhouse,2705 SW Sylvan Heights Dr,Seattle,WA,98106,515000.0,2.0,2.25,1420.0,...,http://www.redfin.com/WA/Seattle/2705-SW-Sylva...,47.539596,-122.368164,Seattle,Washington,WA,69.1,45.0,608660.0,large
10026,2434,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,...,http://www.redfin.com/WA/Shoreline/3020-NE-145...,47.734004,-122.295562,Shoreline,Washington,WA,69.1,45.0,53007.0,large
10027,4869,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,...,http://www.redfin.com/WA/Shoreline/3020-NE-145...,47.734004,-122.295562,Shoreline,Washington,WA,69.1,45.0,53007.0,large
10028,2085,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,...,http://www.redfin.com/WA/Vancouver/730-SE-Fair...,45.615925,-122.652918,Vancouver,Washington,WA,79.0,33.0,161791.0,large
10029,4520,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,...,http://www.redfin.com/WA/Vancouver/730-SE-Fair...,45.615925,-122.652918,Vancouver,Washington,WA,79.0,33.0,161791.0,large

In [52]:
housing_complete_merge['house_id'] = housing_complete_merge.index + 1

In [53]:
housing_complete_merge

,Unnamed: 0,property_type,address,city,state,zip_code,price,beds,baths,square_feet,...,latitude,longitude,temp_city,temp_state,temp_abbr,Summer Temp,Winter Temp,population,pop_cat,house_id
0,4870,Single Family Residential,32996 Heather Glen Ct,Anchor Point,AK,99556.0,369900.0,5.0,3.00,2500.0,...,59.794550,-151.827787,Anchor Point,Alaska,AK,61.0,19.0,1930.0,small,1
1,4871,Single Family Residential,70875 Lee Roy Ave,Anchor Point,AK,99556.0,319000.0,2.0,2.00,1456.0,...,59.845004,-151.787534,Anchor Point,Alaska,AK,61.0,19.0,1930.0,small,2
2,4872,Single Family Residential,26890 Sterling Hwy,Anchor Point,AK,99556.0,115000.0,2.0,1.00,896.0,...,59.882706,-151.782732,Anchor Point,Alaska,AK,61.0,19.0,1930.0,small,3
3,4873,Single Family Residential,31513 Sterling Hwy,Anchor Point,AK,99556.0,205000.0,3.0,1.00,1423.0,...,59.816224,-151.827229,Anchor Point,Alaska,AK,61.0,19.0,1930.0,small,4
4,4874,Single Family Residential,72960 Laida Ave,Anchor Point,AK,99556.0,299000.0,2.0,2.00,2185.0,...,59.781840,-151.851596,Anchor Point,Alaska,AK,61.0,19.0,1930.0,small,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10025,4868,Townhouse,2705 SW Sylvan Heights Dr,Seattle,WA,98106,515000.0,2.0,2.25,1420.0,...,47.539596,-122.368164,Seattle,Washington,WA,69.1,45.0,608660.0,large,10026
10026,2434,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,...,47.734004,-122.295562,Shoreline,Washington,WA,69.1,45.0,53007.0,large,10027
10027,4869,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,...,47.734004,-122.295562,Shoreline,Washington,WA,69.1,45.0,53007.0,large,10028
10028,2085,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,...,45.615925,-122.652918,Vancouver,Washington,WA,79.0,33.0,161791.0,large,10029
10029,4520,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,...,45.615925,-122.652918,Vancouver,Washington,WA,79.0,33.0,161791.0,large,10030

In [54]:
housing_complete_merge.to_csv("housing_complete_for_cleaning_only.csv")

In [55]:
cols = list(housing_complete_merge.columns.values)
cols

['Unnamed: 0',
 'property_type',
 'address',
 'city',
 'state',
 'zip_code',
 'price',
 'beds',
 'baths',
 'square_feet',
 'lot_size',
 'year_built',
 'hoa_permonth',
 'url',
 'latitude',
 'longitude',
 'temp_city',
 'temp_state',
 'temp_abbr',
 'Summer Temp',
 'Winter Temp',
 'population',
 'pop_cat',
 'house_id']

In [56]:
complete_housing_data = housing_complete_merge[['house_id','property_type','address', 'city','state','zip_code',
                                                'price','beds','baths','square_feet','lot_size','year_built',
                                                'hoa_permonth','url', 'latitude','longitude','Summer Temp',
                                                 'Winter Temp','population', 'pop_cat']]

 
complete_housing_data

,house_id,property_type,address,city,state,zip_code,price,beds,baths,square_feet,lot_size,year_built,hoa_permonth,url,latitude,longitude,Summer Temp,Winter Temp,population,pop_cat
0,1,Single Family Residential,32996 Heather Glen Ct,Anchor Point,AK,99556.0,369900.0,5.0,3.00,2500.0,404672.0,2016.0,0.0,http://www.redfin.com/AK/Unknown/32996-HEATHER...,59.794550,-151.827787,61.0,19.0,1930.0,small
1,2,Single Family Residential,70875 Lee Roy Ave,Anchor Point,AK,99556.0,319000.0,2.0,2.00,1456.0,125452.0,2002.0,0.0,http://www.redfin.com/AK/Anchor-Point/70875-Le...,59.845004,-151.787534,61.0,19.0,1930.0,small
2,3,Single Family Residential,26890 Sterling Hwy,Anchor Point,AK,99556.0,115000.0,2.0,1.00,896.0,86248.0,2009.0,0.0,http://www.redfin.com/AK/Anchor-Point/26890-St...,59.882706,-151.782732,61.0,19.0,1930.0,small
3,4,Single Family Residential,31513 Sterling Hwy,Anchor Point,AK,99556.0,205000.0,3.0,1.00,1423.0,78408.0,1962.0,0.0,http://www.redfin.com/AK/Anchor-Point/31513-St...,59.816224,-151.827229,61.0,19.0,1930.0,small
4,5,Single Family Residential,72960 Laida Ave,Anchor Point,AK,99556.0,299000.0,2.0,2.00,2185.0,78843.0,1998.0,0.0,http://www.redfin.com/AK/Anchor-Point/72960-La...,59.781840,-151.851596,61.0,19.0,1930.0,small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10025,10026,Townhouse,2705 SW Sylvan Heights Dr,Seattle,WA,98106,515000.0,2.0,2.25,1420.0,1245.0,2007.0,190.0,http://www.redfin.com/WA/Seattle/2705-SW-Sylva...,47.539596,-122.368164,69.1,45.0,608660.0,large
10026,10027,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,6135.0,1947.0,0.0,http://www.redfin.com/WA/Shoreline/3020-NE-145...,47.734004,-122.295562,69.1,45.0,53007.0,large
10027,10028,Single Family Residential,3020 NE 145th St,Shoreline,WA,98155,599000.0,3.0,1.00,1020.0,6135.0,1947.0,0.0,http://www.redfin.com/WA/Shoreline/3020-NE-145...,47.734004,-122.295562,69.1,45.0,53007.0,large
10028,10029,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,0.0,2001.0,237.0,http://www.redfin.com/WA/Vancouver/730-SE-Fair...,45.615925,-122.652918,79.0,33.0,161791.0,large
10029,10030,Condo/Co-op,730 SE Fairwinds Loop,Vancouver,WA,98661,365000.0,3.0,2.00,1324.0,0.0,2001.0,237.0,http://www.redfin.com/WA/Vancouver/730-SE-Fair...,45.615925,-122.652918,79.0,33.0,161791.0,large

In [57]:
training_data = housing_complete_merge[['house_id','price','beds','baths','square_feet','lot_size',
                                                'hoa_permonth', 'Summer Temp','Winter Temp','population']]

training_data

,house_id,price,beds,baths,square_feet,lot_size,hoa_permonth,Summer Temp,Winter Temp,population
0,1,369900.0,5.0,3.00,2500.0,404672.0,0.0,61.0,19.0,1930.0
1,2,319000.0,2.0,2.00,1456.0,125452.0,0.0,61.0,19.0,1930.0
2,3,115000.0,2.0,1.00,896.0,86248.0,0.0,61.0,19.0,1930.0
3,4,205000.0,3.0,1.00,1423.0,78408.0,0.0,61.0,19.0,1930.0
4,5,299000.0,2.0,2.00,2185.0,78843.0,0.0,61.0,19.0,1930.0
...,...,...,...,...,...,...,...,...,...,...
10025,10026,515000.0,2.0,2.25,1420.0,1245.0,190.0,69.1,45.0,608660.0
10026,10027,599000.0,3.0,1.00,1020.0,6135.0,0.0,69.1,45.0,53007.0
10027,10028,599000.0,3.0,1.00,1020.0,6135.0,0.0,69.1,45.0,53007.0
10028,10029,365000.0,3.0,2.00,1324.0,0.0,237.0,79.0,33.0,161791.0
10029,10030,365000.0,3.0,2.00,1324.0,0.0,237.0,79.0,33.0,161791.0

In [58]:
complete_housing_data.to_csv('housing_complete_data.csv')

In [59]:
training_data_dropna = training_data.dropna()

In [60]:
training_data_dropna

,house_id,price,beds,baths,square_feet,lot_size,hoa_permonth,Summer Temp,Winter Temp,population
0,1,369900.0,5.0,3.00,2500.0,404672.0,0.0,61.0,19.0,1930.0
1,2,319000.0,2.0,2.00,1456.0,125452.0,0.0,61.0,19.0,1930.0
2,3,115000.0,2.0,1.00,896.0,86248.0,0.0,61.0,19.0,1930.0
3,4,205000.0,3.0,1.00,1423.0,78408.0,0.0,61.0,19.0,1930.0
4,5,299000.0,2.0,2.00,2185.0,78843.0,0.0,61.0,19.0,1930.0
...,...,...,...,...,...,...,...,...,...,...
10025,10026,515000.0,2.0,2.25,1420.0,1245.0,190.0,69.1,45.0,608660.0
10026,10027,599000.0,3.0,1.00,1020.0,6135.0,0.0,69.1,45.0,53007.0
10027,10028,599000.0,3.0,1.00,1020.0,6135.0,0.0,69.1,45.0,53007.0
10028,10029,365000.0,3.0,2.00,1324.0,0.0,237.0,79.0,33.0,161791.0
10029,10030,365000.0,3.0,2.00,1324.0,0.0,237.0,79.0,33.0,161791.0

In [61]:
training_data_dropna.to_csv('../housing_training_data.csv', index=False)

In [62]:
print(len(complete_housing_data.index))

test_results = complete_housing_data.dropna()
print(len(test_results.index))

print("lost rows: " + str(len(complete_housing_data.index) - len(test_results.index)))

10030
10027
lost rows: 3