In [6]:
import pandas as pd

In [7]:
population = pd.read_csv('../population/population_categories.csv')
population

         state        city  population pop_cat
0      Alabama   Abbeville        2688  middle
1      Alabama  Adamsville        4522  middle
2      Alabama     Addison         758   small
3      Alabama       Akron         356   small
4      Alabama   Alabaster       30352  middle
...        ...         ...         ...     ...
19418  Wyoming   Wamsutter         451   small
19419  Wyoming   Wheatland        3627  middle
19420  Wyoming     Worland        5487  middle
19421  Wyoming      Wright        1807   small
19422  Wyoming       Yoder         151   small

[19423 rows x 4 columns]

In [8]:
population_sorted = population.sort_values(by=['state', 'city'])
population_sorted

         state        city  population pop_cat
0      Alabama   Abbeville        2688  middle
1      Alabama  Adamsville        4522  middle
2      Alabama     Addison         758   small
3      Alabama       Akron         356   small
4      Alabama   Alabaster       30352  middle
...        ...         ...         ...     ...
19418  Wyoming   Wamsutter         451   small
19419  Wyoming   Wheatland        3627  middle
19420  Wyoming     Worland        5487  middle
19421  Wyoming      Wright        1807   small
19422  Wyoming       Yoder         151   small

[19423 rows x 4 columns]

In [9]:
temp_data = pd.read_csv('../temperature/original_files/redfin_temps_complete.csv')
temp_data

      temp_city     temp_state temp_abbr  Summer Temp  Winter Temp
0    Birmingham        Alabama        AL         82.1         45.1
1    Huntsville        Alabama        AL         80.0         42.9
2        Mobile        Alabama        AL         82.8         51.5
3    Montgomery        Alabama        AL         83.7         48.5
4     Alexander       Arkansas        AR         81.9         41.8
..          ...            ...       ...          ...          ...
469  Huntington  West Virginia        WV         75.3         35.1
470      Casper        Wyoming        WY         69.7         26.9
471    Cheyenne        Wyoming        WY         70.5         31.0
472      Lander        Wyoming        WY         70.9         17.9
473    Sheridan        Wyoming        WY         69.3         27.1

[474 rows x 5 columns]

In [10]:
temp_data_sorted = temp_data.sort_values(by=['temp_state', 'temp_city'])
temp_data_sorted

         temp_city temp_state temp_abbr  Summer Temp  Winter Temp
0       Birmingham    Alabama        AL         82.1         45.1
1       Huntsville    Alabama        AL         80.0         42.9
2           Mobile    Alabama        AL         82.8         51.5
3       Montgomery    Alabama        AL         83.7         48.5
16       Flagstaff    Arizona        AZ         67.3         30.8
..             ...        ...       ...          ...          ...
470         Casper    Wyoming        WY         69.7         26.9
471       Cheyenne    Wyoming        WY         70.5         31.0
472         Lander    Wyoming        WY         70.9         17.9
473       Sheridan    Wyoming        WY         69.3         27.1
101  Washington DC        NaN        DC         84.0         27.0

[474 rows x 5 columns]

In [11]:
temp_data_sorted.dtypes

temp_city       object
temp_state      object
temp_abbr       object
Summer Temp    float64
Winter Temp    float64
dtype: object

In [12]:

temp_data_sorted.loc[:,'temp_city'] = temp_data_sorted.loc[:, 'temp_city'].astype("string")
temp_data_sorted.loc[:,'temp_state'] = temp_data_sorted.loc[:, 'temp_state'].astype("string")
temp_data_sorted.loc[:,'temp_abbr'] = temp_data_sorted.loc[:, 'temp_abbr'].astype("string")

In [13]:
temp_data_sorted.dtypes

temp_city       string
temp_state      string
temp_abbr       string
Summer Temp    float64
Winter Temp    float64
dtype: object

In [14]:
pop_temp_merge = temp_data_sorted.merge(population_sorted, how="left", left_on=['temp_state', 'temp_city'], right_on=['state', 'city'])

In [15]:
pop_temp_merge

,temp_city,temp_state,temp_abbr,Summer Temp,Winter Temp,state,city,population,pop_cat
0,Birmingham,Alabama,AL,82.1,45.1,Alabama,Birmingham,212237.0,large
1,Huntsville,Alabama,AL,80.0,42.9,Alabama,Huntsville,180105.0,large
2,Mobile,Alabama,AL,82.8,51.5,Alabama,Mobile,195111.0,large
3,Montgomery,Alabama,AL,83.7,48.5,Alabama,Montgomery,205764.0,large
4,Flagstaff,Arizona,AZ,67.3,30.8,Arizona,Flagstaff,65870.0,large
...,...,...,...,...,...,...,...,...,...
469,Casper,Wyoming,WY,69.7,26.9,Wyoming,Casper,55316.0,large
470,Cheyenne,Wyoming,WY,70.5,31.0,Wyoming,Cheyenne,59466.0,large
471,Lander,Wyoming,WY,70.9,17.9,Wyoming,Lander,7487.0,middle
472,Sheridan,Wyoming,WY,69.3,27.1,Wyoming,Sheridan,17444.0,middle
473,Washington DC,<NA>,DC,84.0,27.0,NaN,NaN,NaN,NaN

In [16]:
pop_temp_drop_col = pop_temp_merge.drop(columns=['state', 'city'])

In [17]:
pop_temp_drop_col

,temp_city,temp_state,temp_abbr,Summer Temp,Winter Temp,population,pop_cat
0,Birmingham,Alabama,AL,82.1,45.1,212237.0,large
1,Huntsville,Alabama,AL,80.0,42.9,180105.0,large
2,Mobile,Alabama,AL,82.8,51.5,195111.0,large
3,Montgomery,Alabama,AL,83.7,48.5,205764.0,large
4,Flagstaff,Arizona,AZ,67.3,30.8,65870.0,large
...,...,...,...,...,...,...,...
469,Casper,Wyoming,WY,69.7,26.9,55316.0,large
470,Cheyenne,Wyoming,WY,70.5,31.0,59466.0,large
471,Lander,Wyoming,WY,70.9,17.9,7487.0,middle
472,Sheridan,Wyoming,WY,69.3,27.1,17444.0,middle
473,Washington DC,<NA>,DC,84.0,27.0,NaN,NaN

## JOINING HOUSING

In [18]:
redfin_data = pd.read_csv('../redfin_housing/redfin_resources/combined_regions/redfin_all_regions.csv')

In [19]:
redfin_data

,Unnamed: 0,property_type,address,city,state,zip_code,price,beds,baths,square_feet,lot_size,year_built,hoa_permonth,url,latitude,longitude
0,0,Vacant Land,000 Avilla E,Alexander,AR,72002,600000,0,0.0,0,2613600,unknown,0,http://www.redfin.com/AR/Beaver-Township/Avill...,34.683729,-92.581063
1,1,Single Family Residential,9015 Springhill Rd,Alexander,AR,72002,175000,5,2.0,2556,69696,1974,0,http://www.redfin.com/AR/Alexander/9015-Spring...,34.673700,-92.523410
2,2,Single Family Residential,7105 Woodsgate Cv,Alexander,AR,72002,158800,3,2.0,1452,12196,2020,8,http://www.redfin.com/AR/Alexander/7105-Woodsg...,34.629537,-92.441267
3,3,Single Family Residential,5072 Peace Ln,Alexander,AR,72002,329900,4,3.5,2550,9583,2020,0,http://www.redfin.com/AR/Alexander/5072-Peace-...,34.670127,-92.507217
4,4,Mobile/Manufactured Home,15900 Shirley Dr,Alexander,AR,72002,21000,2,1.0,1124,13939,1983,0,http://www.redfin.com/AR/Alexander/15900-Shirl...,34.606398,-92.444045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5257,1020,Townhouse,310 Amber Dr #31,Whitewater,WI,53190,235000,4,3.5,2552,0,2006,300,http://www.redfin.com/WI/Whitewater/310-Amber-...,42.821893,-88.724786
5258,1021,Single Family Residential,531 Wilmette Rd,Williams Bay,WI,53191,719000,3,2.0,1624,5662,1969,0,http://www.redfin.com/WI/Williams-Bay/531-Wilm...,42.577095,-88.528413
5259,1022,Vacant Land,Lt1 Congress St,Williams Bay,WI,53191,99900,0,0.0,0,19602,unknown,0,http://www.redfin.com/WI/Williams-Bay/Lt1-Cong...,42.575006,-88.544436
5260,1023,Single Family Residential,Lt188 Bailey Ests Unit ''Georgian'',Williams Bay,WI,53191,386490,4,2.5,3177,22651,unknown,0,http://www.redfin.com/WI/Williams-Bay/471-Ashl...,42.596684,-88.557406
5261,1024,Single Family Residential,Lt187 Bailey Ests Unit ''Bailey'',Williams Bay,WI,53191,303490,3,2.0,1870,22651,unknown,0,http://www.redfin.com/WI/Williams-Bay/471-Ashl...,42.596684,-88.557406

In [20]:
redfin_sort_state = redfin_data.sort_values(by=['state', 'city'])
redfin_sort_state

,Unnamed: 0,property_type,address,city,state,zip_code,price,beds,baths,square_feet,lot_size,year_built,hoa_permonth,url,latitude,longitude
0,0,Vacant Land,000 Avilla E,Alexander,AR,72002,600000,0,0.0,0,2613600,unknown,0,http://www.redfin.com/AR/Beaver-Township/Avill...,34.683729,-92.581063
1,1,Single Family Residential,9015 Springhill Rd,Alexander,AR,72002,175000,5,2.0,2556,69696,1974,0,http://www.redfin.com/AR/Alexander/9015-Spring...,34.673700,-92.523410
2,2,Single Family Residential,7105 Woodsgate Cv,Alexander,AR,72002,158800,3,2.0,1452,12196,2020,8,http://www.redfin.com/AR/Alexander/7105-Woodsg...,34.629537,-92.441267
3,3,Single Family Residential,5072 Peace Ln,Alexander,AR,72002,329900,4,3.5,2550,9583,2020,0,http://www.redfin.com/AR/Alexander/5072-Peace-...,34.670127,-92.507217
4,4,Mobile/Manufactured Home,15900 Shirley Dr,Alexander,AR,72002,21000,2,1.0,1124,13939,1983,0,http://www.redfin.com/AR/Alexander/15900-Shirl...,34.606398,-92.444045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5257,1020,Townhouse,310 Amber Dr #31,Whitewater,WI,53190,235000,4,3.5,2552,0,2006,300,http://www.redfin.com/WI/Whitewater/310-Amber-...,42.821893,-88.724786
5258,1021,Single Family Residential,531 Wilmette Rd,Williams Bay,WI,53191,719000,3,2.0,1624,5662,1969,0,http://www.redfin.com/WI/Williams-Bay/531-Wilm...,42.577095,-88.528413
5259,1022,Vacant Land,Lt1 Congress St,Williams Bay,WI,53191,99900,0,0.0,0,19602,unknown,0,http://www.redfin.com/WI/Williams-Bay/Lt1-Cong...,42.575006,-88.544436
5260,1023,Single Family Residential,Lt188 Bailey Ests Unit ''Georgian'',Williams Bay,WI,53191,386490,4,2.5,3177,22651,unknown,0,http://www.redfin.com/WI/Williams-Bay/471-Ashl...,42.596684,-88.557406
5261,1024,Single Family Residential,Lt187 Bailey Ests Unit ''Bailey'',Williams Bay,WI,53191,303490,3,2.0,1870,22651,unknown,0,http://www.redfin.com/WI/Williams-Bay/471-Ashl...,42.596684,-88.557406

In [21]:
redfin_sort_dropna = redfin_sort_state.dropna()
redfin_sort_dropna

,Unnamed: 0,property_type,address,city,state,zip_code,price,beds,baths,square_feet,lot_size,year_built,hoa_permonth,url,latitude,longitude
0,0,Vacant Land,000 Avilla E,Alexander,AR,72002,600000,0,0.0,0,2613600,unknown,0,http://www.redfin.com/AR/Beaver-Township/Avill...,34.683729,-92.581063
1,1,Single Family Residential,9015 Springhill Rd,Alexander,AR,72002,175000,5,2.0,2556,69696,1974,0,http://www.redfin.com/AR/Alexander/9015-Spring...,34.673700,-92.523410
2,2,Single Family Residential,7105 Woodsgate Cv,Alexander,AR,72002,158800,3,2.0,1452,12196,2020,8,http://www.redfin.com/AR/Alexander/7105-Woodsg...,34.629537,-92.441267
3,3,Single Family Residential,5072 Peace Ln,Alexander,AR,72002,329900,4,3.5,2550,9583,2020,0,http://www.redfin.com/AR/Alexander/5072-Peace-...,34.670127,-92.507217
4,4,Mobile/Manufactured Home,15900 Shirley Dr,Alexander,AR,72002,21000,2,1.0,1124,13939,1983,0,http://www.redfin.com/AR/Alexander/15900-Shirl...,34.606398,-92.444045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5257,1020,Townhouse,310 Amber Dr #31,Whitewater,WI,53190,235000,4,3.5,2552,0,2006,300,http://www.redfin.com/WI/Whitewater/310-Amber-...,42.821893,-88.724786
5258,1021,Single Family Residential,531 Wilmette Rd,Williams Bay,WI,53191,719000,3,2.0,1624,5662,1969,0,http://www.redfin.com/WI/Williams-Bay/531-Wilm...,42.577095,-88.528413
5259,1022,Vacant Land,Lt1 Congress St,Williams Bay,WI,53191,99900,0,0.0,0,19602,unknown,0,http://www.redfin.com/WI/Williams-Bay/Lt1-Cong...,42.575006,-88.544436
5260,1023,Single Family Residential,Lt188 Bailey Ests Unit ''Georgian'',Williams Bay,WI,53191,386490,4,2.5,3177,22651,unknown,0,http://www.redfin.com/WI/Williams-Bay/471-Ashl...,42.596684,-88.557406
5261,1024,Single Family Residential,Lt187 Bailey Ests Unit ''Bailey'',Williams Bay,WI,53191,303490,3,2.0,1870,22651,unknown,0,http://www.redfin.com/WI/Williams-Bay/471-Ashl...,42.596684,-88.557406

In [22]:
pop_temp_drop_col.sort_values(by=['temp_state', 'temp_city'])
pop_temp_drop_col

,temp_city,temp_state,temp_abbr,Summer Temp,Winter Temp,population,pop_cat
0,Birmingham,Alabama,AL,82.1,45.1,212237.0,large
1,Huntsville,Alabama,AL,80.0,42.9,180105.0,large
2,Mobile,Alabama,AL,82.8,51.5,195111.0,large
3,Montgomery,Alabama,AL,83.7,48.5,205764.0,large
4,Flagstaff,Arizona,AZ,67.3,30.8,65870.0,large
...,...,...,...,...,...,...,...
469,Casper,Wyoming,WY,69.7,26.9,55316.0,large
470,Cheyenne,Wyoming,WY,70.5,31.0,59466.0,large
471,Lander,Wyoming,WY,70.9,17.9,7487.0,middle
472,Sheridan,Wyoming,WY,69.3,27.1,17444.0,middle
473,Washington DC,<NA>,DC,84.0,27.0,NaN,NaN

In [23]:
housing_complete_merge = redfin_sort_dropna.merge(pop_temp_drop_col, how="left", left_on=['state', 'city'], right_on=['temp_abbr', 'temp_city'])
housing_complete_merge

,Unnamed: 0,property_type,address,city,state,zip_code,price,beds,baths,square_feet,...,url,latitude,longitude,temp_city,temp_state,temp_abbr,Summer Temp,Winter Temp,population,pop_cat
0,0,Vacant Land,000 Avilla E,Alexander,AR,72002,600000,0,0.0,0,...,http://www.redfin.com/AR/Beaver-Township/Avill...,34.683729,-92.581063,Alexander,Arkansas,AR,81.9,41.8,2901.0,middle
1,1,Single Family Residential,9015 Springhill Rd,Alexander,AR,72002,175000,5,2.0,2556,...,http://www.redfin.com/AR/Alexander/9015-Spring...,34.673700,-92.523410,Alexander,Arkansas,AR,81.9,41.8,2901.0,middle
2,2,Single Family Residential,7105 Woodsgate Cv,Alexander,AR,72002,158800,3,2.0,1452,...,http://www.redfin.com/AR/Alexander/7105-Woodsg...,34.629537,-92.441267,Alexander,Arkansas,AR,81.9,41.8,2901.0,middle
3,3,Single Family Residential,5072 Peace Ln,Alexander,AR,72002,329900,4,3.5,2550,...,http://www.redfin.com/AR/Alexander/5072-Peace-...,34.670127,-92.507217,Alexander,Arkansas,AR,81.9,41.8,2901.0,middle
4,4,Mobile/Manufactured Home,15900 Shirley Dr,Alexander,AR,72002,21000,2,1.0,1124,...,http://www.redfin.com/AR/Alexander/15900-Shirl...,34.606398,-92.444045,Alexander,Arkansas,AR,81.9,41.8,2901.0,middle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5926,1020,Townhouse,310 Amber Dr #31,Whitewater,WI,53190,235000,4,3.5,2552,...,http://www.redfin.com/WI/Whitewater/310-Amber-...,42.821893,-88.724786,Whitewater,Wisconsin,WI,80.0,11.0,14390.0,middle
5927,1021,Single Family Residential,531 Wilmette Rd,Williams Bay,WI,53191,719000,3,2.0,1624,...,http://www.redfin.com/WI/Williams-Bay/531-Wilm...,42.577095,-88.528413,Williams Bay,Wisconsin,WI,80.0,10.0,NaN,NaN
5928,1022,Vacant Land,Lt1 Congress St,Williams Bay,WI,53191,99900,0,0.0,0,...,http://www.redfin.com/WI/Williams-Bay/Lt1-Cong...,42.575006,-88.544436,Williams Bay,Wisconsin,WI,80.0,10.0,NaN,NaN
5929,1023,Single Family Residential,Lt188 Bailey Ests Unit ''Georgian'',Williams Bay,WI,53191,386490,4,2.5,3177,...,http://www.redfin.com/WI/Williams-Bay/471-Ashl...,42.596684,-88.557406,Williams Bay,Wisconsin,WI,80.0,10.0,NaN,NaN
5930,1024,Single Family Residential,Lt187 Bailey Ests Unit ''Bailey'',Williams Bay,WI,53191,303490,3,2.0,1870,...,http://www.redfin.com/WI/Williams-Bay/471-Ashl...,42.596684,-88.557406,Williams Bay,Wisconsin,WI,80.0,10.0,NaN,NaN

In [24]:
housing_complete_merge['house_id'] = housing_complete_merge.index + 1

In [25]:
housing_complete_merge

,Unnamed: 0,property_type,address,city,state,zip_code,price,beds,baths,square_feet,...,latitude,longitude,temp_city,temp_state,temp_abbr,Summer Temp,Winter Temp,population,pop_cat,house_id
0,0,Vacant Land,000 Avilla E,Alexander,AR,72002,600000,0,0.0,0,...,34.683729,-92.581063,Alexander,Arkansas,AR,81.9,41.8,2901.0,middle,1
1,1,Single Family Residential,9015 Springhill Rd,Alexander,AR,72002,175000,5,2.0,2556,...,34.673700,-92.523410,Alexander,Arkansas,AR,81.9,41.8,2901.0,middle,2
2,2,Single Family Residential,7105 Woodsgate Cv,Alexander,AR,72002,158800,3,2.0,1452,...,34.629537,-92.441267,Alexander,Arkansas,AR,81.9,41.8,2901.0,middle,3
3,3,Single Family Residential,5072 Peace Ln,Alexander,AR,72002,329900,4,3.5,2550,...,34.670127,-92.507217,Alexander,Arkansas,AR,81.9,41.8,2901.0,middle,4
4,4,Mobile/Manufactured Home,15900 Shirley Dr,Alexander,AR,72002,21000,2,1.0,1124,...,34.606398,-92.444045,Alexander,Arkansas,AR,81.9,41.8,2901.0,middle,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5926,1020,Townhouse,310 Amber Dr #31,Whitewater,WI,53190,235000,4,3.5,2552,...,42.821893,-88.724786,Whitewater,Wisconsin,WI,80.0,11.0,14390.0,middle,5927
5927,1021,Single Family Residential,531 Wilmette Rd,Williams Bay,WI,53191,719000,3,2.0,1624,...,42.577095,-88.528413,Williams Bay,Wisconsin,WI,80.0,10.0,NaN,NaN,5928
5928,1022,Vacant Land,Lt1 Congress St,Williams Bay,WI,53191,99900,0,0.0,0,...,42.575006,-88.544436,Williams Bay,Wisconsin,WI,80.0,10.0,NaN,NaN,5929
5929,1023,Single Family Residential,Lt188 Bailey Ests Unit ''Georgian'',Williams Bay,WI,53191,386490,4,2.5,3177,...,42.596684,-88.557406,Williams Bay,Wisconsin,WI,80.0,10.0,NaN,NaN,5930
5930,1024,Single Family Residential,Lt187 Bailey Ests Unit ''Bailey'',Williams Bay,WI,53191,303490,3,2.0,1870,...,42.596684,-88.557406,Williams Bay,Wisconsin,WI,80.0,10.0,NaN,NaN,5931

In [26]:
housing_complete_merge.to_csv("housing_complete_for_cleaning_only.csv")

In [27]:
cols = list(housing_complete_merge.columns.values)
cols

['Unnamed: 0',
 'property_type',
 'address',
 'city',
 'state',
 'zip_code',
 'price',
 'beds',
 'baths',
 'square_feet',
 'lot_size',
 'year_built',
 'hoa_permonth',
 'url',
 'latitude',
 'longitude',
 'temp_city',
 'temp_state',
 'temp_abbr',
 'Summer Temp',
 'Winter Temp',
 'population',
 'pop_cat',
 'house_id']

In [28]:
complete_housing_data = housing_complete_merge[['house_id','property_type','address', 'city','state','zip_code',
                                                'price','beds','baths','square_feet','lot_size','year_built',
                                                'hoa_permonth','url', 'latitude','longitude','Summer Temp',
                                                 'Winter Temp','population', 'pop_cat']]

 
complete_housing_data

,house_id,property_type,address,city,state,zip_code,price,beds,baths,square_feet,lot_size,year_built,hoa_permonth,url,latitude,longitude,Summer Temp,Winter Temp,population,pop_cat
0,1,Vacant Land,000 Avilla E,Alexander,AR,72002,600000,0,0.0,0,2613600,unknown,0,http://www.redfin.com/AR/Beaver-Township/Avill...,34.683729,-92.581063,81.9,41.8,2901.0,middle
1,2,Single Family Residential,9015 Springhill Rd,Alexander,AR,72002,175000,5,2.0,2556,69696,1974,0,http://www.redfin.com/AR/Alexander/9015-Spring...,34.673700,-92.523410,81.9,41.8,2901.0,middle
2,3,Single Family Residential,7105 Woodsgate Cv,Alexander,AR,72002,158800,3,2.0,1452,12196,2020,8,http://www.redfin.com/AR/Alexander/7105-Woodsg...,34.629537,-92.441267,81.9,41.8,2901.0,middle
3,4,Single Family Residential,5072 Peace Ln,Alexander,AR,72002,329900,4,3.5,2550,9583,2020,0,http://www.redfin.com/AR/Alexander/5072-Peace-...,34.670127,-92.507217,81.9,41.8,2901.0,middle
4,5,Mobile/Manufactured Home,15900 Shirley Dr,Alexander,AR,72002,21000,2,1.0,1124,13939,1983,0,http://www.redfin.com/AR/Alexander/15900-Shirl...,34.606398,-92.444045,81.9,41.8,2901.0,middle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5926,5927,Townhouse,310 Amber Dr #31,Whitewater,WI,53190,235000,4,3.5,2552,0,2006,300,http://www.redfin.com/WI/Whitewater/310-Amber-...,42.821893,-88.724786,80.0,11.0,14390.0,middle
5927,5928,Single Family Residential,531 Wilmette Rd,Williams Bay,WI,53191,719000,3,2.0,1624,5662,1969,0,http://www.redfin.com/WI/Williams-Bay/531-Wilm...,42.577095,-88.528413,80.0,10.0,NaN,NaN
5928,5929,Vacant Land,Lt1 Congress St,Williams Bay,WI,53191,99900,0,0.0,0,19602,unknown,0,http://www.redfin.com/WI/Williams-Bay/Lt1-Cong...,42.575006,-88.544436,80.0,10.0,NaN,NaN
5929,5930,Single Family Residential,Lt188 Bailey Ests Unit ''Georgian'',Williams Bay,WI,53191,386490,4,2.5,3177,22651,unknown,0,http://www.redfin.com/WI/Williams-Bay/471-Ashl...,42.596684,-88.557406,80.0,10.0,NaN,NaN
5930,5931,Single Family Residential,Lt187 Bailey Ests Unit ''Bailey'',Williams Bay,WI,53191,303490,3,2.0,1870,22651,unknown,0,http://www.redfin.com/WI/Williams-Bay/471-Ashl...,42.596684,-88.557406,80.0,10.0,NaN,NaN

In [29]:
training_data = housing_complete_merge[['house_id','price','beds','baths','square_feet','lot_size',
                                                'hoa_permonth', 'Summer Temp','Winter Temp','population']]

training_data

,house_id,price,beds,baths,square_feet,lot_size,hoa_permonth,Summer Temp,Winter Temp,population
0,1,600000,0,0.0,0,2613600,0,81.9,41.8,2901.0
1,2,175000,5,2.0,2556,69696,0,81.9,41.8,2901.0
2,3,158800,3,2.0,1452,12196,8,81.9,41.8,2901.0
3,4,329900,4,3.5,2550,9583,0,81.9,41.8,2901.0
4,5,21000,2,1.0,1124,13939,0,81.9,41.8,2901.0
...,...,...,...,...,...,...,...,...,...,...
5926,5927,235000,4,3.5,2552,0,300,80.0,11.0,14390.0
5927,5928,719000,3,2.0,1624,5662,0,80.0,10.0,NaN
5928,5929,99900,0,0.0,0,19602,0,80.0,10.0,NaN
5929,5930,386490,4,2.5,3177,22651,0,80.0,10.0,NaN
5930,5931,303490,3,2.0,1870,22651,0,80.0,10.0,NaN

In [30]:
complete_housing_data.to_csv('housing_complete_data.csv')

In [31]:
training_data.to_csv('../housing_training_data.csv', index=False)